// frontendframeworks_angular_webapp/src/main/webapp/angular-webapp/src/app/components/note/note.component.ts
import {Component, OnInit} from '@angular/core';
import {NoteService} from "../../services/note.service";
import {ActivatedRoute, Router} from "@angular/router";

@Component({
    selector: 'note',
    templateUrl: './note.component.html',
    styleUrls: ['./note.component.css'],
    providers: [NoteService]
})
export class NoteComponent implements OnInit {

    note = {};
    private noteId: string;

    constructor(private noteService: NoteService,
                private router: Router,
                private route: ActivatedRoute) {

        route.params.subscribe(p => {
            this.noteId = p['id'];
        });
    }

    navigateBack() {
        this.router.navigate(['/notes']);
    }

    getNote() {
        this.noteService.getNote(this.noteId)
            .then(result => this.note = result);
    }

    editNote() {
        this.noteService.updateNote(this.note);
    }

    ngOnInit() {
        this.getNote();
    }

}

<div class="container">

  <div class="card">

    <div class="card-header">
      Note Details
    </div>

    <div class="card-body">

      <div class="card">

        <button (click)="navigateBack()"
                type="button"
                class="btn btn-primary">
          < Back
        </button>

        <div class="card-body">

          <form #editNoteForm="ngForm">

            <div class="form-group">
              <label for="titleId">Note Title</label>
              <input [(ngModel)]="note.title"
                     name="title"
                     required
                     id="titleId"
                     type="text"
                     class="form-control"
                     aria-describedby="basic-addon2">
            </div>

            <div class="form-group">
              <label for="descriptionId">Note Description</label>
              <textarea [(ngModel)]="note.description"
                        name="description"
                        required
                        id="descriptionId"
                        class="form-control">
              </textarea>
            </div>

            <button (click)="editNote()"
                    [disabled]="!editNoteForm.valid"
                    [ngClass]="{disabled: !editNoteForm.valid}"
                    class="btn btn btn-primary"
                    type="button">
              Edit Note
            </button>

          </form>

        </div>
      </div>
    </div>
  </div>

</div>

// frontendframeworks_vuejs_webapp/src/main/webapp/vuejs-app/src/components/Note.vue
<template>

    <div class="container">

        <div class="card">
            <button type="button"
                    class="btn btn-primary">
                <router-link to="/">
                    <span style="color: white">Back</span>
                </router-link>
            </button>

            <div class="card-body">

                <div class="form-group">
                    <label for="titleId">Note Title</label>
                    <input v-model="note.title"
                           name="title"
                           id="titleId"
                           type="text"
                           class="form-control"
                           aria-describedby="basic-addon2">
                </div>

                <div class="form-group">
                    <label for="descriptionId">Note Description</label>
                    <textarea v-model="note.description"
                              name="description"
                              id="descriptionId"
                              class="form-control">
                    </textarea>
                </div>

                <button v-on:click="editNote()"
                        class="btn btn btn-primary"
                        type="button">
                    Edit Note
                </button>

            </div>
        </div>

    </div>

</template>

<script>

    import {getNote, updateNote} from "../services/NoteService";

    export default {
        name: 'Note',
        methods: {

            getNote() {

                const noteId = this.$route.query.uid;
                getNote(noteId)
                    .then(response => {
                        this.note = response.data;
                    })
                    .catch(() => {
                        // error handler
                    });
            },

            editNote() {

                updateNote(this.note)
                    .then(() => {
                        this.getNote();
                    })
                    .catch(() => {
                        // error handler
                    });
            }
        },
        data: function () {
            return {
                note: {
                    title: '',
                    description: ''
                }
            }
        },
        beforeMount() {
            this.getNote();
        }
    }

</script>
